### ISSUE TITLE
PowerShell Language Server fails to start due to incorrect path on Windows

### ISSUE THREAD

**Issue by vkibalyuk** [wingyplus/zed-powershell#16]
<details><summary>Log:</summary>
<p>

```
2025-06-24T17:49:53+03:00 INFO  [lsp] starting language server process. binary path: "C:\\Program Files\\PowerShell\\7\\pwsh.exe", working directory: "D:\\", args: ["-NoLogo", "-NoProfile", "-Command", "Import-Module ( Join-Path \'/C:\\Users\\dtt\\AppData\\Local\\Zed\\extensions\\work\\powershell/powershell-es-v4.3.0\' \'PowerShellEditorServices/PowerShellEditorServices.psd1\' ); Start-EditorServices -Stdio -SessionDetailsPath \'/C:\\Users\\dtt\\AppData\\Local\\Zed\\extensions\\work\\powershell/powershell-es-v4.3.0/powershell-es.session.json\' -LogPath \'/C:\\Users\\dtt\\AppData\\Local\\Zed\\extensions\\work\\powershell/powershell-es-v4.3.0/logs\' -FeatureFlags @() -AdditionalModules @() -HostName zed -HostProfileId 0 -HostVersion 1.0.0 -LogLevel Trace"]
2025-06-24T17:49:53+03:00 ERROR [lsp] cannot read LSP message headers
2025-06-24T17:49:53+03:00 ERROR [lsp] Server reset connection for a request "initialize" id 0
2025-06-24T17:49:53+03:00 ERROR [project::lsp_store] Failed to start language server "powershell-es": Error {
    context: "initializing server powershell-es, id 11",
    source: "Server reset the connection",
}
2025-06-24T17:49:53+03:00 ERROR [project::lsp_store] server stderr: [31;1mImport-Module: [31;1mCannot find drive. A drive with the name '\C' does not exist.[0m
[31;1mStart-EditorServices: [31;1mThe term 'Start-EditorServices' is not recognized as a name of a cmdlet, function, script file, or executable program.[0m
[31;1m[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.[0m

2025-06-24T17:49:53+03:00 ERROR [lsp] server shut down
```

</p>
</details>

**Comment by GennaroRiccio** [comment]
same issue

**Comment by adevries17** [comment]
I was able to get it to start up using the following configuration:

```json
"lsp": {
    "powershell-es": {
      "binary": {
        "path": "pwsh.exe",
        "arguments": [
          "-NoLogo",
          "-NoProfile",
          "-Command",
          "C:\\bin\\PowerShellEditorServices\\PowerShellEditorServices\\Start-EditorServices.ps1",
          "-Stdio"
        ]
      }
    }
```

**Comment by adevries17** [comment]
I was able to get it running with the following configuration in my settings.json. Replace the '<user>' with yours which I believe is 'dtt'.

```json
  "lsp": {
    "powershell-es": {
      "binary": {
        "path": "pwsh.exe",
        "arguments": [
          "-NoLogo",
          "-NoProfile",
          "-Command",
          "C:\\Users\\<user>\\AppData\\Local\\Zed\\extensions\\work\\powershell\\powershell-es-v4.3.0\\PowerShellEditorServices\\Start-EditorServices.ps1",
          "-Stdio",
          "-SessionDetailsPath",
          "C:\\Users\\<user>\\AppData\\Local\\Zed\\extensions\\work\\powershell\\powershell-es-v4.3.0\\PowerShellEditorServices\\powershell-es.session.json"
        ]
      }
    }

```

**Comment by GennaroRiccio** [comment]
@adevries17 work for me, tnx!

**Comment by WithHolm** [comment]
it kinda seemes like single quotes are escaped. why this happens on windows and not linux i couldn't tell you as im not a rust person, however. can possibly r# strings work? it kinda looks nicer and you can use double quotations if you define 2 `#`.

```rust
let command = format!(
    r##"
        $Module = Join-Path "{bundle_path}" "PowerShellEditorServices" "PowerShellEditorServices.psd1";
        $SessionDetails = Join-Path "{bundle_path}" "powershell-es.session.json";
        $Log = Join-Path "{bundle_path}" "logs";

        Import-Module $module;

        Start-EditorServices `
            -Stdio `
            -SessionDetailsPath $SessionDetails `
            -LogPath $Log `
            -FeatureFlags @() `
            -AdditionalModules @() `
            -HostName "zed" `
            -HostProfileId 0 `
            -HostVersion "1.0.0" `
            -LogLevel "trace";
"##
);
```

for any pwsh people: I also tried splatting the command (making a hashtable and then using that as function param input), but rust seemes to expect a variable every time you start a curly bracket, and i'm not good enough at rust to really know how to fix that, so backtick notation is the next best thing.

i couldnt get the dev extension functionality to work for me, but it seemes to build just fine, so someone else would have to add this :)

**Comment by vkibalyuk** [comment]
This works for me on Windows, I've adopted workaround by @WithHolm
```rust
        use std::path::{self, Path};

        let command = format!(
            r#"
                $Module = Join-Path "{0}" "PowerShellEditorServices" "PowerShellEditorServices.psd1"
                $SessionDetails = Join-Path "{0}" "powershell-es.session.json"
                $Log = Join-Path "{0}" "logs"

                Import-Module $Module

                Start-EditorServices `
                    -Stdio `
                    -SessionDetailsPath $SessionDetails `
                    -LogPath $Log `
                    -FeatureFlags @() `
                    -AdditionalModules @() `
                    -HostName "zed" `
                    -HostProfileId 0 `
                    -HostVersion "1.0.0" `
                    -LogLevel "Trace"
            "#,
            Path::new(&bundle_path)
                .to_str()
                .ok_or("invalid unicode in bundle_path")?
                .strip_prefix('/')
                .unwrap_or_else(|| bundle_path.as_str())
        );
```

**Comment by wingyplus** [comment]
Anyone want to open a PR to tackle this?

**Comment by vkibalyuk** [comment]
Done #18 
Not sure if it's the best way to do it, I'm still new to Rust.

**Comment by Sansui233** [comment]
> [@vkibalyuk](https://github.com/vkibalyuk) I clean installed too. I opened the folder `C:\Users\%USERNAME%\AppData\Local\Zed\extensions\work\powershell` and there's nothing there. Something went wrong with the download of the LSP.
> 
> I commented out the LSP block I posted above, installed the extension normally, then uncommented the LSP block and it downloaded just fine.
> 
> Do you have the same behavior?

The same

**Comment by MrSubidubi** [comment]
I think this should be resolved as of Zed version 0.205.x. The workaround within the PR should not be needed anymore. Is anyone stil running into this?

**Comment by olehub** [comment]
> I think this should be resolved as of Zed version 0.205.x. The workaround within the PR should not be needed anymore. Is anyone stil running into this?

The problem still persists with the latest nightly and the PowerShell extension `v0.3.0`.
Running `Zed: v0.208.0 (Zed Nightly e4f90b5da2b8a6d2b267edc02b333b7d7908d4d9)`

**Comment by MrSubidubi** [comment]
Yep, sorry for the false information from my side! See https://github.com/wingyplus/zed-powershell/pull/18#issuecomment-3362128213 - what would have to happen here for this to be fixed is a version bump of the `zed_extension_api` to the latest version for this to be resolved.

**Comment by olehub** [comment]
With the following config, powershell-es works, but leaks the pwsh.exe and conhost.exe processes on change of workspace via `Open Recent...` or zed application exit.

### Update:
Tested application exit and `Open Recent...` several times. The result:
- Applikcation exit still leaks pwsh.exe
- `Open Recent...` normally does not leak pwsh.exe, i could not reproduce the one and only leak.

``` json
  "lsp": {
    "powershell-es": {
      "binary": {
        "path": "pwsh.exe",
        "arguments": [
          "-NoLogo",
          "-NoProfile",
          "-Command",
          "C:\\Users\\Oliver\\AppData\\Local\\Zed\\extensions\\work\\powershell\\powershell-es-v4.4.0\\PowerShellEditorServices\\Start-EditorServices.ps1",
          "-Stdio",
          "-SessionDetailsPath",
          "C:\\Users\\Oliver\\AppData\\Local\\Zed\\extensions\\work\\powershell\\powershell-es-v4.4.0\\PowerShellEditorServices\\powershell-es.session.json"
        ]
      }
    }
  }
```

**Comment by olehub** [comment]
@MrSubidubi Still no visible progress.

**Comment by shanto** [comment]
Zed v0.209.5 / PowerShell v0.3.0
```
Language server powershell-es:

initializing server powershell-es, id 1: Server reset the connection
-- stderr --
[31;1mImport-Module: [31;1mCannot find drive. A drive with the name '\C' does not exist.[0m
[31;1mStart-EditorServices: [31;1mThe term 'Start-EditorServices' is not recognized as a name of a cmdlet, function, script file, or executable program.[0m
[31;1m[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.[0m
```

**Comment by Derjyn** [comment]
I'm getting errors as well, there isn't anything in the directory others were noting as a "fix".

```
Language server powershell-es:

initializing server powershell-es, id 2: Server reset the connection
-- stderr --
[31;1mC:\Users\<redacted>\AppData\Local\Zed\extensions\work\powershell\powershell-es-v4.3.0\PowerShellEditorServices\Start-EditorServices.ps1: [31;1mThe term 'C:\Users\<redacted>\AppData\Local\Zed\extensions\work\powershell\powershell-es-v4.3.0\PowerShellEditorServices\Start-EditorServices.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.[0m
[31;1m[31;1mCheck the spelling of the name, or if a path was included, verify that the path is correct and try again.[0m
```

**Comment by olehub** [comment]
@Derjyn Have you tried https://github.com/wingyplus/zed-powershell/issues/16#issuecomment-3058678369 ?
You could also get the PowerShellEditorServices from vscode, it is just a different path, then.

**Comment by lucaspimentel** [comment]
> what would have to happen here for this to be fixed is a version bump of the `zed_extension_api` to the latest version for this to be resolved.

I created a PR to update the `zed_extension_api` dependency in the extension: #28.

`Cargo.toml`:
```diff
[dependencies]
- zed_extension_api = "0.2.0"
+ zed_extension_api = "0.7.0"
```

I loaded [my fork](https://github.com/lucaspimentel/zed-powershell) locally as a dev extension on Zed 0.216.1 and the PowerShell LS seems to load correctly now.

edit 2026-03-16: closed my PR since this is now fixed (see below).

**Comment by shanto** [comment]
@lucaspimentel your fix works perfectly. Thank you

**Comment by MrSubidubi** [comment]
We decided to fork the extension for the time being and also fixed the bug in the fork via https://github.com/zed-extensions/powershell/pull/3. I will roll out a new version in the next few minutes that will finally fix this with the released version. Sorry for the inconvenience.
